### ISSUE TITLE
スポンサーロゴの掲載

### ISSUE THREAD

**Issue by jiyuujin** [FlutterKaigi/2022#25]
[協賛のご案内](https://docs.google.com/presentation/d/1HEwDIi6rxzKUnZmu7EKkwR04bvTQnSjWjpw3ldunczM/edit?usp=sharing) より各種プランに申し込んだ企業・組織のロゴを掲載する

- プラチナ
- ゴールド
- シルバー
- ブロンズ
- 配信

**Comment by okaryo** [comment]
ロゴ置き場はこちら？
https://github.com/FlutterKaigi/Resources/tree/main/sponsors

fortee上でのスポンサー数17社に対して、8/28時点でロゴは8社分

**Comment by jiyuujin** [comment]
はい、そちらに各社 svg ロゴがあれば (無ければ svg ロゴを吐き出すなどで) それを使ってください
https://github.com/FlutterKaigi/Resources/tree/main/sponsors

**Comment by okaryo** [comment]
@jiyuujin 
ご確認ありがとうございます！
ロゴが集まった段階で対応させていただきます！

**Comment by okaryo** [comment]
掲載するロゴはfortee上の17社 + DeNAさん(ゴールド相当) + LayerX(ブロンズ相当)さんの計19社

**Comment by okaryo** [comment]
DeNAさんのロゴも集まったようです。
これから着手開始します。

- アトラエさんはキャンセルされたので、掲載するロゴはfortee上の16社 + DeNAさん + LayerX(ブロンズ相当)さんの計18社
- Figma
  - https://www.figma.com/file/3jxi4kkyBLUNw1lHfFGHzs/FlutterKaigi?node-id=109%3A49
